import Link from 'next/link';

export const metadata = {
  title: 'Terms of Service — AngleMotion',
  description: 'Terms of service for the AngleMotion coaching platform.',
};

export default function TermsPage() {
  return (
    <div style={{
      height: '100dvh',
      overflowY: 'auto',
      WebkitOverflowScrolling: 'touch',
      background: 'linear-gradient(160deg, #0a0a10 0%, #0f1420 100%)',
      color: '#fff',
      fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    }}>
      <div style={{
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        padding: '12px 20px', borderBottom: '1px solid rgba(255,255,255,0.07)',
        background: 'rgba(0,0,0,0.4)', backdropFilter: 'blur(12px)',
        position: 'sticky', top: 0, zIndex: 20,
      }}>
        <Link href="/" style={{ display: 'flex', alignItems: 'center', gap: 8, textDecoration: 'none' }}>
          <img src="/logo-square-new.jpg" alt="AngleMotion" style={{ width: 28, height: 28, borderRadius: 6 }} />
          <span style={{ fontSize: 14, fontWeight: 800, color: '#fff' }}>
            Angle<span style={{ color: '#FF3B30' }}>Motion</span>
          </span>
        </Link>
        <Link href="/privacy" style={{
          fontSize: 12, fontWeight: 600, color: 'rgba(255,255,255,0.7)', textDecoration: 'none',
          padding: '6px 14px', borderRadius: 20, border: '1px solid rgba(255,255,255,0.2)',
        }}>
          Privacy Policy
        </Link>
      </div>

      <main style={{ maxWidth: 760, margin: '0 auto', padding: '48px 20px 80px', lineHeight: 1.65 }}>
        <h1 style={{ fontSize: 32, fontWeight: 900, letterSpacing: -0.5, margin: '0 0 6px' }}>Terms of Service – AngleMotion</h1>
        <p style={{ color: 'rgba(255,255,255,0.55)', fontSize: 13, margin: '0 0 36px' }}>Effective Date: July 3, 2026</p>

        <Section title="Company: AngleMotion">
          AngleMotion ("we", "us", "our")
        </Section>

        <Section title="1. Introduction">
          These Terms of Service govern access to and use of the AngleMotion web and mobile application and related services ("Service"). By using the Service, you agree to these Terms.
        </Section>

        <Section title="2. Acceptance of Terms">
          By creating an account or using the Service, you confirm that you have read, understood, and agree to be bound by these Terms. If you do not agree, you must not use the Service.
        </Section>

        <Section title="3. Description of the Service">
          AngleMotion provides video analysis tools designed for sports performance improvement, primarily tennis. Users can upload or connect video content to receive biomechanical and technical analysis.
          <br /><br />
          The Service may allow users to:
          <ul style={{ marginTop: 12, marginBottom: 0 }}>
            <li>Upload video files directly</li>
            <li>Connect external accounts (such as Google services)</li>
            <li>Store and process training-related media</li>
            <li>Export analysis reports</li>
          </ul>
        </Section>

        <Section title="4. Google API Services Usage Disclosure">
          AngleMotion uses Google API Services only when explicitly authorized by the user.
          <br /><br />
          We request access to the following Google scopes solely to provide core functionality:
        </Section>

        <Section title="4.1 YouTube Data API">
          Used only to:
          <ul style={{ marginTop: 12, marginBottom: 12 }}>
            <li>Allow users to upload videos to their own YouTube account from within AngleMotion</li>
            <li>Retrieve basic video metadata required for upload confirmation</li>
          </ul>
          We do not:
          <ul style={{ marginTop: 12, marginBottom: 0 }}>
            <li>Access private YouTube data unrelated to user-selected uploads</li>
            <li>Use YouTube data for advertising or profiling</li>
          </ul>
        </Section>

        <Section title="4.2 Google Drive API">
          Used only to:
          <ul style={{ marginTop: 12, marginBottom: 12 }}>
            <li>Access files selected by the user for video analysis</li>
            <li>Store analysis outputs if the user chooses Google Drive as storage destination</li>
          </ul>
          We do not:
          <ul style={{ marginTop: 12, marginBottom: 0 }}>
            <li>Access all files in a user's Drive</li>
            <li>Read or modify files without explicit user selection</li>
          </ul>
        </Section>

        <Section title="4.3 Google Docs API">
          Used only to:
          <ul style={{ marginTop: 12, marginBottom: 12 }}>
            <li>Create or export analysis reports generated by the user's video sessions</li>
            <li>Save documents to locations explicitly selected by the user</li>
          </ul>
          We do not:
          <ul style={{ marginTop: 12, marginBottom: 0 }}>
            <li>Read existing Google Docs content unless explicitly selected by the user</li>
            <li>Share documents with third parties</li>
          </ul>
        </Section>

        <Section title="4.4 Data Handling Principles (Google Data)">
          We strictly comply with Google API Services User Data Policy, including:
          <ul style={{ marginTop: 12, marginBottom: 0 }}>
            <li>Access only the minimum data required for the feature requested</li>
            <li>No transfer, sale, or monetization of Google user data</li>
            <li>No use of Google user data for advertising, profiling, or analytics outside service functionality</li>
            <li>No sharing of Google user data with unauthorized third parties</li>
          </ul>
        </Section>

        <Section title="5. User Data and Privacy">
          We collect and process only data necessary to operate the Service, including:
          <ul style={{ marginTop: 12, marginBottom: 12 }}>
            <li>Account information (email, authentication identifiers)</li>
            <li>Uploaded or connected training videos</li>
            <li>User-generated analysis data</li>
          </ul>
          We do not sell personal data. All processing is done solely to provide core functionality of the application.
        </Section>

        <Section title="6. Data Retention and Deletion">
          Users retain full control over their data.
          <ul style={{ marginTop: 12, marginBottom: 12 }}>
            <li>Users may delete uploaded content at any time</li>
            <li>Users may disconnect Google accounts at any time</li>
            <li>Upon deletion request, associated data is permanently removed within a reasonable timeframe</li>
            <li>Google-derived data is deleted when the user revokes access</li>
          </ul>
        </Section>

        <Section title="7. User Rights and Account Termination">
          Users may:
          <ul style={{ marginTop: 12, marginBottom: 12 }}>
            <li>Access their data</li>
            <li>Modify or delete their content</li>
            <li>Revoke third-party integrations</li>
          </ul>
          We may suspend accounts in case of misuse or violation of these Terms.
        </Section>

        <Section title="8. Security Measures">
          We implement reasonable technical and organizational measures to protect user data, including encryption in transit and access controls. However, no system is fully secure, and we cannot guarantee absolute security.
        </Section>

        <Section title="9. Third-Party Services">
          The Service integrates with:
          <ul style={{ marginTop: 12, marginBottom: 12 }}>
            <li>Google API Services (YouTube, Drive, Docs)</li>
          </ul>
          Use of these services is subject to their respective terms and privacy policies.
        </Section>

        <Section title="10. Limitation of Liability">
          To the maximum extent permitted by law, AngleMotion is not liable for indirect damages, loss of data, or service interruptions.
        </Section>

        <Section title="11. Changes to Terms">
          We may update these Terms periodically. Continued use of the Service constitutes acceptance of the updated Terms.
        </Section>

        <Section title="12. Contact Information">
          For questions regarding these Terms, contact: <a href="mailto:vinbaccelli@gmail.com" style={a}>vinbaccelli@gmail.com</a>
        </Section>
      </main>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section style={{ marginBottom: 32 }}>
      <h2 style={{ fontSize: 19, fontWeight: 800, margin: '0 0 10px', letterSpacing: -0.2 }}>{title}</h2>
      <div style={{ fontSize: 14.5, color: 'rgba(255,255,255,0.82)' }}>{children}</div>
    </section>
  );
}

const a: React.CSSProperties = { color: '#4DA3FF', textDecoration: 'underline' };